name: Build and Package macOS Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19' # Specify your Go version

      - name: Install dependencies
        run: |
          go mod tidy
          cd frontend && pnpm install && cd ..

      - name: Build macOS application (amd64)
        run: |
          cd frontend
          pnpm run build
          cd ..
          task build:darwin:prod:amd64

      - name: Package macOS application (amd64)
        run: task package:darwin:amd64

      - name: Upload macOS package (amd64)
        uses: actions/upload-artifact@v3
        with:
          name: macos-amd64-app
          path: path/to/your/packaged/app # Update this path to where your app is generated

      - name: Build macOS application (arm64)
        run: |
          cd frontend
          pnpm run build
          cd ..
          task build:darwin:prod:arm64

      - name: Package macOS application (arm64)
        run: task package:darwin:arm64

      - name: Upload macOS package (arm64)
        uses: actions/upload-artifact@v3
        with:
          name: macos-arm64-app
          path: path/to/your/packaged/app # Update this path to where your app is generated
